### ISSUE TITLE
Modification for HTML5 manifests and offline web pages

### ISSUE THREAD

**Issue by stakach** [robatron/jquery.scale#3]
Added the following code between lines 61 and 62 in commit dated: 2010-04-01
This is to support cached content when using HTML5 manifests. This code maintains the same image (removing the datetime parameter) in all browsers except IE 6 to 8 as IE does not support manifest files anyway and all other browsers will still scale the image.

This post is primarily being made to maintain compliance to the GPLv3. Please feel free to contact me if you would like a complete copy of the file. I did not feel this change was prominent enough to require a new branch.

if ($.support.leadingWhitespace)    // For app side as ie 6-8 requires a new image for scaling
   obj.attr("src", cursrc);

**Comment by robatron** [comment]
Added. Let me know if it doesn't work :)

**Comment by stakach** [comment]
Works a charm. Can close the "Plugin does not work in Internet Explorer" issue now too.

**Comment by stakach** [comment]
Also, not sure if it is related to this or opera just got better however at least for me jquery scale has worked in opera since version 10.

**Comment by robatron** [comment]
Awesome, thanks for letting me know. I was hoping to avoid installing Windows :)
