### ISSUE TITLE
Use .data() instead of .attr()

### ISSUE THREAD

**Issue by stakach** [robatron/jquery.scale#5]
obj.data('jquery_scale_orig-height')
obj.data('jquery_scale_orig-width')

instead of

obj.attr('jquery_scale_orig-height')
obj.attr('jquery_scale_orig-width')

data is still stored in the DOM and is much faster than attr

**Comment by robatron** [comment]
Indeed. I don't think I knew about data() when I wrote this. I'll look into it.

**Comment by robatron** [comment]
Done. Seems to work just fine with the changes :)
